{% set version = "0.0.32" %}

package:
  name: aeppl-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aeppl/aeppl-{{ version }}.tar.gz
  sha256: 2730542eaa5e3a10335c8b4f048b379ee1283c7ee03b9ab234268363eed3307d
  patches:

build:
  number: 0
  # The following line seems to do nothing. Place noarch in the build block of individual outputs.
  noarch: python

outputs:
  - name: aeppl-base
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps -vv
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - numpy >=1.18.1
        - scipy >=1.4.0
        - aesara-base >=2.3.2
    test:
      imports:
        - aeppl
      commands:
        - pip check
      requires:
        - pip

  - name: aeppl
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('aeppl-base', exact=True) }}
        # As of Aesara v2.7.5, there is a 1-1 correspondence between the "aesara-base"
        # package and the "aesara" package of the same version and build number on
        # which it depends. Thus the pin from the "aesara-base" package above will
        # implicitly transfer here to the "aesara" package.
        - aesara >=2.7.5
    test:
      imports:
        - aeppl
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/aesara-devs/aeppl
  license: MIT
  summary: PPL tools for Aesara
  license_file: LICENSE
  dev_url: https://github.com/aesara-devs/aeppl/

extra:
  recipe-maintainers:
    - brandonwillard
    - ricardoV94
    - twiecki
